### ISSUE TITLE
Can't install 1.0.9 (to use Guzzle 7)

### ISSUE THREAD

**Issue by fantasticmachine** [ethercreative/web-payments#25]
I'm trying to install the latest version but getting dependency errors about Guzzle.

I see that this was supposedly fixed in 1.0.9 but that version doesn't appear to be available to install despite being the latest release.

Running `composer require ether/web-payments` tries to install 1.0.8 and gives the error
```
Problem 1
    - ether/web-payments[1.0.0, ..., 1.0.8] require guzzlehttp/guzzle ^6.3.3 -> found guzzlehttp/guzzle[6.3.3, ..., 6.5.5] but the package is fixed to 7.4.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires ether/web-payments ^1.0 -> satisfiable by ether/web-payments[1.0.0, ..., 1.0.8].
    ```
    
Running `composer require ether/web-payments:1.0.9` gives the error 
`[InvalidArgumentException]                                                                               
  Could not find package ether/web-payments in a version matching "1.0.9" and a stability matching "dev".`

**Comment by alexjcollins** [comment]
@Tam would you mind checking this one out for us?

**Comment by fantasticmachine** [comment]
FYI the version shown as available in the plugin store is 1.0.8

**Comment by williamhibberd** [comment]
I have also just bumped into this issue. I can't seem to install 1.0.9, and am getting the same dependency error as @fantasticmachine 

Any suggestions on how to get the plugin working?

**Comment by goodmixer** [comment]
Same issue here.

**Comment by john-henry** [comment]
Any chance of getting 1.0.9 up on packagist?
