### ISSUE TITLE
Craft 4

### ISSUE THREAD

**Issue by williamhibberd** [ethercreative/web-payments#28]
Just wondering if you are planning on getting web-payments updated for use on v4 of craft?

**Comment by alexjcollins** [comment]
Hey @williamhibberd — it's on our list, but I unfortunately don't have a timeline. I'm hopeful it'll be in the next month or two.

**Comment by robzor** [comment]
Hi there, any update on getting a Craft 4 version of this plugin in the store? We'd love to use it (and so would our client)!

Thanks

**Comment by jamie-jenks** [comment]
I'm also looking to see when you guys plan on releasing the Craft 4 version as we've got a few clients looking to make the upgrade 👍
