### ISSUE TITLE
[Feature request] Reinitialize JS

### ISSUE THREAD

**Issue by 23d1** [ethercreative/web-payments#3]
I'm not sure if there is already functionality around this implemented. A way to reinitialize the button would be great.

Use case; ajaxified site loads the cart page, or a portion thereof containing the payment button html. Button needs to be reinitialized once the new html is inserted.

Would something like running `window.CraftWebPayments();` suffice?

**Comment by Tam** [comment]
@23d1 I've added a `reload` function to the buttons object:

```twig
{{ craft.webPayments.button({
    items: [{ id: 1, qty: 1 }],
    js: 'window.payButton',
}) }}
```
```js
window.payButton = window.payButton.reload();
```
