### ISSUE TITLE
IntegrationError: The paymentRequestButton Element is not available in the current environment.

### ISSUE THREAD

**Issue by olsp** [ethercreative/web-payments#9]
I use the web-payments plugin but the Pay Button doesn't show up. In the console I get the following error: "IntegrationError: The paymentRequestButton Element is not available in the current environment."

Stripe is in live mode (with live API keys) and the craft environment is production.

Which other environment do I need to change for this to work?

**Comment by Tam** [comment]
It could be a couple of things. Firstly you need to be using a browser on a platform that supports web payments (i.e. Safari on iOS). Second, you need to make sure your chosen currency and store country are supported by your Stripe account. For example, if your Stripe account is UK based but your Commerce store address is US based, you'll need to change these to match.

**Comment by olsp** [comment]
I checked all those things but I'm pretty sure all of this is correct.
Do you have any other ideas what could cause this error?

**Comment by davecosec** [comment]
@olsp You need a valid SSL certificate aswell.

**Comment by olsp** [comment]
@davecosec thanks for your comment. If https is not active, I actually get a helpful error message "IntegrationError: Live Stripe.js integrations must use HTTPS." So this isn't the problem, I only get this on my local machine, on the server I use HTTPS.

**Comment by alexjcollins** [comment]
@olsp If you think you've exhausted all options your end we might need to pick this up with you via email so we can see if we can recreate.

Could you ping an email to dev@ethercreative.co.uk with the following info (plus anything else about your setup you think might be useful to us):
- Commerce Store Address
- Stripe Account Address
- Payment Currency on Commerce
- Stripe Account Currency
- A database dump if you're able to

**Comment by olsp** [comment]
@alexjcollins thanks for your offer, have you received my email? Could you find anything I did wrong?

**Comment by alexjcollins** [comment]
@olsp How long ago did you send it? It may have gone into spam.
Could you try resending it for me? Thanks!

**Comment by olsp** [comment]
@alexjcollins Two weeks ago (May 5th), but just sent it again.
Thanks!

**Comment by alexjcollins** [comment]
Thanks – all received!

**Comment by olsp** [comment]
@alexjcollins I think I solved it! I used `{{ craft.webPayments.button({ cart: cart }) }}` but need to use: `{{ craft.webPayments.button({ cart: craft.commerce.carts.cart }) }}`

I just used `cart: cart` because I'm on the cart page and for everything else I just use `cart`. For example `{% for item in cart.lineItems %}`

**Comment by alexjcollins** [comment]
Glad to hear it!

Thanks for letting us know too, as it was on the list to check out in the next day or so.

I’ll close the issue, but feel free to let us know if there’s anything else.
